[kijanikiosk_api]
api-staging ansible_host=35.189.252.163

[kijanikiosk_payments]
payments-staging ansible_host=34.78.149.195

[kijanikiosk_logs]
logs-staging ansible_host=34.76.135.54

[kijanikiosk:children]
kijanikiosk_api
kijanikiosk_payments
kijanikiosk_logs

[kijanikiosk:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_user=rovenelabanga2001
ansible_ssh_private_key_file=~/.ssh/kijanikiosk-key